version: '2'
services:
    jhipsterprimengapp-app:
        image: jhipsterprimengapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterprimengapp-mysql:3306/jhipsterprimengapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterprimengapp-mysql:
        extends:
            file: mysql.yml
            service: jhipsterprimengapp-mysql
